
spring:
  profiles:
     active:
       - dev

---
spring:
  profiles: dev      #开发环境
  application:
     name: hello-spring-cloud-web-admin-feign-dev
   
---
 
spring:
  profiles: test     #测试环境
  application:
     name: hello-spring-cloud-web-admin-feign-test